FROM alpine:3.18

RUN apk add --no-cache ca-certificates

RUN set -eux; \
# https://github.com/distribution/distribution/releases
	version='2.8.2-beta.2'; \
	apkArch="$(apk --print-arch)"; \
	case "$apkArch" in \
		x86_64)  arch='amd64';   sha256='f16957fe46a797439892bcea255c9e98477b47a56e03df4906e920eb2db57c28' ;; \
		aarch64) arch='arm64';   sha256='f1c713711bf547185b82139bb4413b0409a6849be918dc29ea08ec04a6f72806' ;; \
		armhf)   arch='armv6';   sha256='364d4da480737627849892e4656bccdda4370007fac655b02e0c3cebe87e14a6' ;; \
		armv7)   arch='armv7';   sha256='e989455bd142736873fbd77ea6e574a079958644527d8716e381fc6545a91a8a' ;; \
		ppc64le) arch='ppc64le'; sha256='377f0f56d4a9eab32630856a6357b245d89050137e433b538c35aafc3b713580' ;; \
		s390x)   arch='s390x';   sha256='66f63e84d7adf02d0b7d8a821c618c464970de3d1726dd1a13c2149a71798f53' ;; \
		*) echo >&2 "error: unsupported architecture: $apkArch"; exit 1 ;; \
	esac; \
	wget -O registry.tar.gz "https://github.com/distribution/distribution/releases/download/v${version}/registry_${version}_linux_${arch}.tar.gz"; \
	echo "$sha256 *registry.tar.gz" | sha256sum -c -; \
	tar --extract --verbose --file registry.tar.gz --directory /bin/ registry; \
	rm registry.tar.gz; \
	registry --version

COPY ./config-example.yml /etc/docker/registry/config.yml

VOLUME ["/var/lib/registry"]
EXPOSE 5000

COPY docker-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["/etc/docker/registry/config.yml"]
